### ISSUE TITLE
Get rid of circle for initial microphone button

### ISSUE THREAD

**Issue by edwardcohen** [edwardcohen/recordapp#4]
Use this file: https://www.dropbox.com/s/jsklhfhjiz2gf26/Record%20Button%20No%20Circle.png?dl=0

**Comment by edwardcohen** [comment]
The mic is blurry. Try this file: 
![record button no circle](https://cloud.githubusercontent.com/assets/2018834/19545296/1be78e74-9653-11e6-9803-dd32e0db86d1.png)

**Comment by edwardcohen** [comment]
![siri mic](https://cloud.githubusercontent.com/assets/2018834/19570881/c62c76e4-96c9-11e6-99e3-91fcbd7fdf14.png)

Use this file

**Comment by edwardcohen** [comment]
Also, please raise mic and timer up 15px

**Comment by alexei1118** [comment]
This is not related here, register as new issue.
